name: PHP_CI_master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Create .env from .env.example
        run: cp .env.example .env

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit tests